language: cpp

sudo: required

services:
  - docker

before_install:
  - docker pull brewpi/firmware-compiler
  - cd ./docker
  - docker-compose build 

script:
  - docker-compose run compiler bash build-firmware.sh
  - docker-compose run compiler bash build-tests.sh
  - docker-compose run compiler bash run-tests.sh

notifications:
  slack:
    secure: AoLzFHi7c7sRdcsMIzCgG3amg/1acImECO21Q3LXf6i6++ytqrvgTiQMQp9k1XJq+WVlrRiP7NDl3o8oMQv9nR/xrNXhosYHXVHAYY/B1nh4jl4pp8hPTMQUJcac64w1zbJMMqlABbawelVg8qF4zn+TNX+io8APERoycBpQgT4=

